// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"context"

	"github.com/omniful/go_commons/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*ProductController, error) {
	productRepository := NewProductRepository(db)
	productService := NewProductService(productRepository)
	productController := NewProductController(productService, productRepository)
	return productController, nil
}
