// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package hub

import (
	"context"

	"github.com/omniful/go_commons/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*HubController, error) {
	hubRepository := NewHubRepository(db)
	hubController := NewHubController(hubRepository)
	return hubController, nil
}
