// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package seller

import (
	"context"

	"github.com/omniful/go_commons/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*SellerController, error) {
	sellerRepository := NewSellerRepository()
	sellerController := NewSellerController(sellerRepository)
	return sellerController, nil
}
